---
- hosts: all
  # vars:
  #   PREFIX: /opt/backup_new
  #   ETC_DIR: "{{ PREFIX }}/etc"
  #   VAR_DIR: "{{ PREFIX }}/var"
  #   BIN_DIR: "{{ PREFIX }}/bin"
  tasks:
    - name: Create directories
      become: true
      file:
        path: "{{ item.value }}"
        state: directory
        mode: "0750"
      loop: "{{ paths | dict2items }}"

    # Each host has its own patterns.lst file, stored in the backup-config repo.
    - name: Copy files to etc/
      become: true
      ansible.builtin.copy:
        src: "~/git/backup-config/{{ ansible_hostname }}/patterns.lst"
        dest: "{{ paths.etc }}"
        mode: "0640"

    - name: Copy files to bin/
      become: true
      copy:
        src: "{{ item }}"
        dest: "{{ paths.bin }}"
        mode: "0750"
      loop:
        - src/borg-backup
        - src/borg-mount

    - name: Copy private key
      become: true
      copy:
        content: "{{ hostvars[inventory_hostname].borg_backup[ansible_hostname].private_key }}"
        dest: "{{ paths.var }}/private_key"
        mode: "0600"

    # The public key is only needed on the backup server, but here's how you would copy it.
    # - name: Copy the public key
    #   copy:
    #     content: "{{ hostvars[inventory_hostname].borg_backup[ansible_hostname].public_key }}"
    #     dest: "{{ VAR_DIR }}/public_key"

    - name: Copy config-file
      become: true
      template:
        src: templates/backup.conf.j2
        dest: "{{ paths.etc }}/backup.conf"
        mode: "0660"
