---
- hosts: localhost
  tasks:
    - name: Clone repositories
      git:
        repo: "{{ item.value.repo }}"
        dest: "{{ item.value.dest }}"
        update: true
      loop: "{{ repos | dict2items }}"
      no_log: true
